[package]
name = "mini-jukebox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
crossterm = "0.23"
infer = "0.12.0"
mp3-duration = "0.1.10"
rodio = "0.16.0"
